export const EMAIL_TEMPLATE_FORGET_PASSWORD = 'EMAIL_TEMPLATE_FORGET_PASSWORD';
export const EMAIL_TEMPLATE_CREATE_USER = 'EMAIL_TEMPLATE_CREATE_USER';
export const EMAIL_TEMPLATE_INVOICE_ORDER = 'EMAIL_TEMPLATE_INVOICE_ORDER';
export const EMAIL_TEMPLATE_RECEIPT_ORDER = 'EMAIL_TEMPLATE_RECEIPT_ORDER';
export const EMAIL_TEMPLATE_SLIP_ORDER = 'EMAIL_TEMPLATE_SLIP_ORDER';
const ET_RC_1 = 'EMAIL_TEMPLATE_';
const ET_RC_2 = 'REGISTER_CUSTOMER';
export const EMAIL_TEMPLATE_REGISTER_CUSTOMER = ET_RC_1 + ET_RC_2;
export const EMAIL_TEMPLATE_CUSTOMER_ACTIVE = 'EMAIL_TEMPLATE_CUSTOMER_ACTIVE';
export const EMAIL_TEMPLATE_CUSTOMER_IN_ACTIVE =
  'EMAIL_TEMPLATE_CUSTOMER_IN_ACTIVE';

export default EMAIL_TEMPLATE_FORGET_PASSWORD;
