export const SALUTATION = {
  MR: 'MR',
  MRS: 'MRS',
  MS: 'MS',
  MDM: 'MDM',
  DR: 'DR',
};

export const GENDER = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
};

export const USER_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const PROMOTIONS_TYPE = {
  PERCENTAGE: 'PERCENTAGE',
  CASH_REBATE: 'CASH_REBATE',
  FREE_SHIPPING: 'FREE_SHIPPING',
};

export const PROMOTIONS_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const ORDERS_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  READY_TO_SHIP: 'READY_TO_SHIP',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const ENQUIRY_STATUS = {
  OPEN: 'OPEN',
  QUOTATION_SENT: 'QUOTATION_SENT',
  WON: 'WON',
  LOST: 'LOST',
  CLOSED: 'CLOSED',
};

export const PROMOTION_APPLYFOR = {
  SPECIAL_PRODUCTS: 'SPECIAL_PRODUCTS',
  ALL_PRODUCTS: 'ALL_PRODUCTS',
};

export const PRODUCT_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const BRAND_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const COLOR_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const TAG_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const CATEGORY_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const CUSTOMER_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPEND: 'SUSPEND',
};

export const CUSTOMER_ADDRESS_TYPE = {
  HOME: 'HOME',
  OFFICE: 'OFFICE',
};

export const BLOCK_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
};

export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  APPROVE_FAILED: 'APPROVE_FAILED',
};

export const BLOCK_TYPE = {
  THEME: 'THEME',
  FOR_BLOCK: 'FOR_BLOCK',
  FIXED: 'FIXED',
  BASIC: 'BASIC',
  CUSTOMIZE: 'CUSTOMIZE',
};

export const PAGE_TYPE = {
  CONTENT: 'CONTENT',
  FUNCTION: 'FUNCTION',
  PRODUCT: 'PRODUCT',
  BLOG: 'BLOG',
};

export const APPROVAL_TYPE = {
  REGISTER_CUSTOMER: 'REGISTER_CUSTOMER',
  PAYMENT: 'PAYMENT',
};

export const VARIANT_TYPE = {
  RICHTEXT: 'RICHTEXT',
  PHOTO: 'PHOTO',
  GALLERY: 'GALLERY',
  PRODUCT_LIST: 'PRODUCT_LIST',
  POST_LIST: 'POST_LIST',
  TREE: 'TREE',
  TEXT: 'TEXT',
};

export const SETTING_KEY = {
  GENERAL_SHOP_NAME: 'GENERAL_SHOP_NAME',
  GENERAL_SHOP_ADDRESS: 'GENERAL_SHOP_ADDRESS',
  CURRENCY_SETTING: 'CURRENCY_SETTING',
  PAYMENT_SETTING: 'PAYMENT_SETTING',
  MINIMUM_DELIVERY_VALUE: 'MINIMUM_DELIVERY_VALUE',
  INVENTORY_SETTING: 'INVENTORY_SETTING',
  EMAIL_PROVIDER_APPRAISER_LIST: 'EMAIL_PROVIDER_APPRAISER_LIST',
  EMAIL_PROVIDER_NOTIFICATION_ORDER_EVENT:
    'EMAIL_PROVIDER_NOTIFICATION_ORDER_EVENT',
  EMAIL_PROVIDER_NOTIFICATION_CONTACT_EVENT:
    'EMAIL_PROVIDER_NOTIFICATION_CONTACT_EVENT',
  EMAIL_PROVIDER_MAILER_HOST: 'EMAIL_PROVIDER_MAILER_HOST',
  EMAIL_PROVIDER_MAILER_PORT: 'EMAIL_PROVIDER_MAILER_PORT',
  EMAIL_PROVIDER_MAILER_PUBLIC_NAME: 'EMAIL_PROVIDER_MAILER_PUBLIC_NAME',
  EMAIL_PROVIDER_MAILER_SENDER_NAME: 'EMAIL_PROVIDER_MAILER_SENDER_NAME',
  EMAIL_PROVIDER_MAILER_USERNAME: 'EMAIL_PROVIDER_MAILER_USERNAME',
  EMAIL_PROVIDER_MAILER_PASSWORD: 'EMAIL_PROVIDER_MAILER_PASSWORD',
  EMAIL_TEMPLATE_REGISTER_ACCOUNT_TITLE:
    'EMAIL_TEMPLATE_REGISTER_ACCOUNT_TITLE',
  EMAIL_TEMPLATE_REGISTER_ACCOUNT_TEMPLATE:
    'EMAIL_TEMPLATE_REGISTER_ACCOUNT_TEMPLATE',
  EMAIL_TEMPLATE_REGISTER_USER_TITLE: 'EMAIL_TEMPLATE_REGISTER_USER_TITLE',
  EMAIL_TEMPLATE_REGISTER_USER_TEMPLATE:
    'EMAIL_TEMPLATE_REGISTER_USER_TEMPLATE',
  EMAIL_TEMPLATE_FORGOT_PASSWORD_TITLE: 'EMAIL_TEMPLATE_FORGOT_PASSWORD_TITLE',
  EMAIL_TEMPLATE_FORGOT_PASSWORD_TEMPLATE:
    'EMAIL_TEMPLATE_FORGOT_PASSWORD_TEMPLATE',
  EMAIL_TEMPLATE_INVOICE_TITLE: 'EMAIL_TEMPLATE_INVOICE_TITLE',
  EMAIL_TEMPLATE_INVOICE_TEMPLATE: 'EMAIL_TEMPLATE_INVOICE_TEMPLATE',
  EMAIL_TEMPLATE_RECEIPT_TITLE: 'EMAIL_TEMPLATE_RECEIPT_TITLE',
  EMAIL_TEMPLATE_RECEIPT_ACCOUNT_TEMPLATE:
    'EMAIL_TEMPLATE_RECEIPT_ACCOUNT_TEMPLATE',
  EMAIL_TEMPLATE_SHIPPING_DETAIL_TITLE: 'EMAIL_TEMPLATE_SHIPPING_DETAIL_TITLE',
  EMAIL_TEMPLATE_SHIPPING_DETAIL_TEMPLATE:
    'EMAIL_TEMPLATE_SHIPPING_DETAIL_TEMPLATE',
  EMAIL_TEMPLATE_CONTACT_US_TITLE: 'EMAIL_TEMPLATE_CONTACT_US_TITLE',
  EMAIL_TEMPLATE_CONTACT_US_TEMPLATE: 'EMAIL_TEMPLATE_CONTACT_US_TEMPLATE',

  EMAIL_TEMPLATE_PAYMENT_LOCAL_BANK_TRANSFER_TITLE:
    'EMAIL_TEMPLATE_PAYMENT_LOCAL_BANK_TRANSFER_TITLE',
  EMAIL_TEMPLATE_PAYMENT_LOCAL_BANK_TRANSFER_TEMPLATE:
    'EMAIL_TEMPLATE_PAYMENT_LOCAL_BANK_TRANSFER_TEMPLATE',
  EMAIL_TEMPLATE_PAYMENT_PAYNOW_TITLE: 'EMAIL_TEMPLATE_PAYMENT_PAYNOW_TITLE',
  EMAIL_TEMPLATE_PAYMENT_PAYNOW_TEMPLATE:
    'EMAIL_TEMPLATE_PAYMENT_PAYNOW_TEMPLATE',
  EMAIL_TEMPLATE_PAYMENT_PAYPAL_TITLE: 'EMAIL_TEMPLATE_PAYMENT_PAYPAL_TITLE',
  EMAIL_TEMPLATE_PAYMENT_PAYPAL_TEMPLATE:
    'EMAIL_TEMPLATE_PAYMENT_PAYPAL_TEMPLATE',
  EMAIL_TEMPLATE_ORDER_THANK_YOU_TITLE: 'EMAIL_TEMPLATE_ORDER_THANK_YOU_TITLE',
  EMAIL_TEMPLATE_ORDER_THANK_YOU_TEMPLATE:
    'EMAIL_TEMPLATE_ORDER_THANK_YOU_TEMPLATE',
  EMAIL_TEMPLATE_ORDER_SORRY_TITLE: 'EMAIL_TEMPLATE_ORDER_SORRY_TITLE',
  EMAIL_TEMPLATE_ORDER_SORRY_TEMPLATE: 'EMAIL_TEMPLATE_ORDER_SORRY_TEMPLATE',
};

export const PAYMENT_OPTION = {
  LOCAL_BANK_TRANSFER: 'LOCAL_BANK_TRANSFER',
  CASH_ON_DELIVERY: 'CASH_ON_DELIVERY',
  PAYNOW: 'PAYNOW',
  PAYPAL: 'PAYPAL',
};

export const PAYMENT_STATUS = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
  PROCESSING: 'PROCESSING',
};

export const TEMPLATE_NAME = {
  SUCESS: 'approval-success',
  ERR: 'error',
};

export default {
  SALUTATION,
  GENDER,
  USER_STATUS,
  ORDERS_STATUS,
  ENQUIRY_STATUS,
  PROMOTIONS_TYPE,
  PROMOTION_APPLYFOR,
  PROMOTIONS_STATUS,
  PRODUCT_STATUS,
  BRAND_STATUS,
  COLOR_STATUS,
  TAG_STATUS,
  CATEGORY_STATUS,
  CUSTOMER_STATUS,
  BLOCK_STATUS,
  PAGE_TYPE,
  SETTING_KEY,
  PAYMENT_OPTION,
  PAYMENT_STATUS,
};
