export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CREATE_USER = 'CREATE_USER';
export const INVOICE_ORDER = 'INVOICE_ORDER';
export const RECEIPT_ORDER = 'RECEIPT_ORDER';
export const SLIP_ORDER = 'SLIP_ORDER';
export const REGISTER_CUSTOMER = 'REGISTER_CUSTOMER';
export const CUSTOMER_ACTIVE = 'CUSTOMER_ACTIVE';
export const CUSTOMER_INACTIVE = 'CUSTOMER_INACTIVE';

export const PAYMENT_LOCAL_BANK_TRANSFER = 'PAYMENT_LOCAL_BANK_TRANSFER';
export const PAYMENT_PAYNOW = 'PAYMENT_PAYNOW';
export const PAYMENT_PAYPAL = 'PAYMENT_PAYPAL';
export const ORDER_THANK_YOU = 'ORDER_THANK_YOU';
export const ORDER_SORRY = 'ORDER_SORRY';
export const CONTACT_US = 'CONTACT_US';

export default FORGOT_PASSWORD;
