export const CREATE_CUSTOMER_PUBLISHER = 'CREATE_CUSTOMER_PUBLISHER';
export const UPDATE_CUSTOMER_PUBLISHER = 'UPDATE_CUSTOMER_PUBLISHER';
export const DELETE_CUSTOMER_PUBLISHER = 'DELETE_CUSTOMER_PUBLISHER';
export const CREATE_ORDER_PUBLISHER = 'CREATE_ORDER_PUBLISHER';
export const UPDATE_STATUS_ORDER_PUBLISHER = 'UPDATE_STATUS_ORDER_PUBLISHER';
export const UPDATE_CANCEL_ORDER_PUBLISHER = 'UPDATE_CANCEL_ORDER_PUBLISHER';
